"""Stable API error codes — frontend maps these to localized messages."""

DISP_TEXT_REQUIRED = "disp_text_required"
LOGO_FILE_REQUIRED = "logo_file_required"
BETA_CODE_REQUIRED = "beta_code_required"
BETA_CODE_INVALID = "beta_code_invalid"
BETA_NOT_OPEN = "beta_not_open"
SERVER_ERROR = "server_error"
OUTPUT_FAILED = "output_failed"
PREVIEW_FAILED = "preview_failed"
ADV_FEATURE_DISABLED = "adv_feature_disabled"
ADV_DEPS_MISSING = "adv_deps_missing"
ADV_PROTECT_FAILED = "adv_protect_failed"
HOLO_CAPTURE_UNAVAILABLE = "holo_capture_unavailable"
HOLO_CAPTURE_FAILED = "holo_capture_failed"
